services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    # build: .
    ports:
      - "8080:8080"
      - "50000:50000"
        #    environment:
        #      - JENKINS_OPTS=--httpListenAddress=0.0.0.0
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net:
